env:
    es2021: true
    node: true
extends:
    - eslint:recommended
    - prettier
    - prettier/@typescript-eslint
    - plugin:prettier/recommended
    - plugin:@typescript-eslint/recommended
    - plugin:@typescript-eslint/eslint-recommended
parser: "@typescript-eslint/parser"
parserOptions:
    ecmaVersion: 12
    sourceType: module
    ecmaFeatures:
        modules: true
plugins:
    - "@typescript-eslint"
globals:
    Atomics: readonly
    SharedArrayBuffer: readonly
ignorePatterns:
    - node_modules/**
    - dist/**
rules:
    linebreak-style:
        - error
        - windows
    indent:
        - error
        - 4
    curly:
        - error
        - multi
    quotes:
        - error
        - double
    semi:
        - error
        - always
    prefer-const: error
    eol-last:
        - error
        - always
    no-trailing-spaces: error
    "prettier/prettier":
        - warn
        - endOfLine: auto
        - usePrettierrc: true
    "@typescript-eslint/no-explicit-any": "off"
    "@typescript-eslint/no-var-requires": "off"
    "@typescript-eslint/array-type":
        - error
        - default: array
          readonly: array
    "@typescript-eslint/ban-types":
        - error
        - types:
              Array: "Do not use Array."
              Object: "Do not use Object."
              String: "Do not use String."
    "@typescript-eslint/consistent-type-definitions":
        - error
        - interface
    "@typescript-eslint/consistent-type-assertions":
        - error
        - assertionStyle: as
          objectLiteralTypeAssertions: allow
    "@typescript-eslint/explicit-function-return-type":
        - error
        - allowExpressions: true
    "@typescript-eslint/no-non-null-assertion": "off"
